name: CI + E2E Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        ports:
          - 5432:5432 #GCP-PostgreSQL
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest tests/test_scripts.py

    - name: Spin up Docker environment
      run: |
        docker compose up -d
        sleep 45  # รอ service ขึ้นก่อน เช่น airflow + postgres ##อนาคตจะเปลี่ยนไปใช้วิธีรอแบบอื่นที่ดีกว่านี้

    - name: Run E2E tests
      run: pytest tests/test_e2e_pipeline.py
